# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: &development
  adapter: postgresql
  encoding: utf8
  database: seg_development
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: seg
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *development
  database: seg_test

